# rename this file to config.yaml and put it in custom input dir or in ~/.config/automlbenchmark directory
# in order to have a custom setup, allowing to add custom frameworks definitions (in our case, creating a benchmark for various H2O versions)
---
project_repository: https://github.com/seb-h2o/automlbenchmark

frameworks:
  definition_file:
    - resources/frameworks.yaml
    - '{user}/frameworks.yaml'    # this file is loaded on local side
    - '{input}/frameworks.yaml'   # this file is loaded on remote side (ec2 instance)

aws:
  resource_files:                 # those resources are uploaded to input directory on the remote (ec2) instance, that's why they should represent local paths.
    - '{user}/config.yaml'        # needed remotely as it contains the path to custom framework definitions
    - '{user}/frameworks.yaml'    # the custom framework definitions
  use_docker: false

