repository: openml.github.io/automlbenchmark
theme: jekyll-theme-slate
markdown: kramdown

title: AutoML Benchmark
#description: config description

#sidebar_home_link: true
version: 0.1.0

github:
  repo:	https://github.com/openml/automlbenchmark
